version: 2.1

orbs:
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - python/install-packages:
          pkg-manager: pip
      # Run linting and tests!
      - run:
      # Run Flake8 without checking for module imports at the top
          name: Linter
          command: |
            flake8 src/ --extend-ignore E402
      - run:
          name: Run Tests
          command: pytest src/


# Orchestrate jobs using workflows
workflows:
  main:
    jobs:
      - build-and-test